# GTK Config
exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps


env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps
